// Generated by @farming-labs/next, then edited. The framework derives absolute
// URLs (agent.json baseUrl, skill.md base URL, canonical Link headers) from
// request.url, but Next's `next start` builds request.url from its own listen
// address (localhost:PORT), ignoring Host and X-Forwarded-Host. So every
// request is rebased onto the canonical origin before the framework sees it.
// Caching: most agent formats set Cache-Control s-maxage=3600 for the CDN;
// search (?query=) sends no Cache-Control and llms.txt only max-age=3600, so
// those hit origin per request (or per CDN TTL) under dynamic rendering.

import docsConfig from "@/docs.config";
import { createDocsAPI } from "@farming-labs/next/api";
import { SITE_URL } from "@/lib/site";

const api = createDocsAPI(docsConfig);

function withCanonicalOrigin(request: Request): Request {
  const url = new URL(request.url);
  const canonical = new URL(SITE_URL);
  url.protocol = canonical.protocol;
  url.host = canonical.host;
  url.port = canonical.port;
  return new Request(url, request);
}

export const GET = (request: Request) => api.GET(withCanonicalOrigin(request) as never);
export const POST = (request: Request) => api.POST(withCanonicalOrigin(request) as never);

export const dynamic = "force-dynamic";
