// Generated by @farming-labs/next, then edited: rendered dynamically so that
// request-origin-derived URLs (agent.json baseUrl, skill.md base URL, canonical
// Link headers) reflect the public host instead of the build-time origin.
// The handler sets Cache-Control: s-maxage=3600, so the CDN still caches.

import docsConfig from "@/docs.config";
import { createDocsAPI } from "@farming-labs/next/api";

export const { GET, POST } = createDocsAPI(docsConfig);

export const dynamic = "force-dynamic";
