// Generated by @farming-labs/next, then edited: rendered dynamically so that
// request-origin-derived URLs (agent.json baseUrl, skill.md base URL, canonical
// Link headers) reflect the public host instead of the build-time origin.
// Caching: most agent formats set Cache-Control s-maxage=3600 for the CDN;
// search (?query=) sends no Cache-Control and llms.txt only max-age=3600, so
// those hit origin per request (or per CDN TTL) under dynamic rendering.

import docsConfig from "@/docs.config";
import { createDocsAPI } from "@farming-labs/next/api";

export const { GET, POST } = createDocsAPI(docsConfig);

export const dynamic = "force-dynamic";
