// Flattens app/docs/**/page.mdx into docs7/, a Mintlify-compatible tree that
// Docs7 (context7.com/docs7) publishes and indexes into Context7. The
// docs7-mirror workflow runs this on every PR and commits the result; run
// `pnpm build-docs7` locally only to preview. Never edit docs7/ by hand:
// app/docs is the single source.
//
// Pages are written with Mintlify component names (mdx-components.tsx maps
// them onto fumadocs), so the body only needs the /docs URL prefix dropped,
// the duplicated H1 removed, and code fences labelled the Mintlify way.
// Requires Node 22.18+ for the type-stripped import of lib/site.ts.

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { SITE_DESCRIPTION, SITE_URL } from "../lib/site.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC_DIR = join(ROOT, "app", "docs");
const OUT_DIR = join(ROOT, "docs7");

// Components Mintlify renders. Anything else outside a code fence is a bug in
// the source page, not something to publish.
const ALLOWED_TAGS = new Set([
  "Accordion",
  "AccordionGroup",
  "Card",
  "CodeGroup",
  "Columns",
  "Frame",
  "Note",
  "Step",
  "Steps",
  "Tab",
  "Tabs",
  "Warning",
  "a",
  "img",
]);

// The only JSX expression props authors may write.
const EXPRESSION_PROPS = /<CodeGroup labels=\{\[.*?\]\}>|<Columns cols=\{\d\}>/g;

const GENERATED_NOTICE =
  "{/* Generated by scripts/build-docs7.mjs from app/docs. Do not edit; run `pnpm build-docs7`. */}";

// Build everything in memory first so a failing page leaves docs7/ untouched.
const outputs = new Map();
const pages = new Set();
const links = []; // { from, target } for every site-absolute link, post-rewrite

// Deliberately not a YAML parser: the pages only use single-line scalars plus
// the two-line `sidebar: folderIndexBehavior` block, and anything new must
// fail loudly rather than publish mangled metadata.
function parseFrontmatter(text, name) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${name}: missing frontmatter`);
  const fm = {};
  const lines = match[1].split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line === "sidebar:") {
      if (lines[i + 1]?.trim() !== "folderIndexBehavior: hidden") {
        throw new Error(`${name}: unsupported sidebar frontmatter`);
      }
      fm.hidden = true;
      i++;
      continue;
    }
    const kv = line.match(/^(title|description|order|icon):[ \t]*(.+)$/);
    if (!kv) throw new Error(`${name}: unsupported frontmatter line "${line}"`);
    const quoted = kv[2].trim().match(/^(["'])(.*)\1$/);
    fm[kv[1]] = quoted ? quoted[2] : kv[2].trim();
  }
  for (const key of ["title", "description", "order", "icon"]) {
    if (!fm[key]) throw new Error(`${name}: frontmatter lacks ${key}`);
  }
  fm.order = Number(fm.order);
  if (!Number.isInteger(fm.order)) throw new Error(`${name}: order is not an integer`);
  return { fm, body: match[2] };
}

function parseLabels(expr) {
  return [...expr.matchAll(/(["'])(.*?)\1/g)].map((m) => m[2]);
}

// Rewrites site-absolute links for a root-hosted Mintlify site: /docs/x -> /x,
// and sends /downloads/* to the Next.js site, which keeps serving those files.
// Anything else site-absolute is a 404 on docs.limrun.com itself, so it is
// rejected instead of being silently mapped onto the mirror. Returns the
// rewritten line and the local targets to verify once every page is known.
function rewriteLinks(line, name) {
  const targets = [];
  const rewritten = line.replace(/(\]\(|href="|src=")(\/[^)"#\s]*)/g, (match, open, target) => {
    if (target.startsWith("/downloads/")) return `${open}${SITE_URL}${target}`;
    if (!/^\/(docs(\/|$)|images\/)/.test(target)) {
      throw new Error(`${name}: link ${target} does not exist on the live site`);
    }
    const local = target.replace(/^\/docs(\/|$)/, "/");
    targets.push(local);
    return `${open}${local}`;
  });
  return { line: rewritten, targets };
}

// Transforms one page body. Line-based on purpose: fences can be indented
// (Step bodies) and must pass through untouched, so every rule checks the
// fence state first.
function transformBody(body, name) {
  const out = [];
  const targets = [];
  let fence = null; // opening backtick run while inside a code fence
  let group = null; // { labels, next } while inside a <CodeGroup>
  let h1 = null;

  for (let line of body.split("\n")) {
    const fenceMatch = line.match(/^(\s*)(`{3,})(.*)$/);
    if (fence) {
      if (fenceMatch && fenceMatch[2].length >= fence.length && !fenceMatch[3].trim()) fence = null;
      out.push(line);
      continue;
    }
    if (fenceMatch) {
      const [, indent, marker, rest] = fenceMatch;
      fence = marker;
      // Mintlify labels a fence with the token after the language. A standalone
      // title="x" becomes that token; inside a CodeGroup the tab label wins, as
      // it does in components/code-group.tsx, and any filename title is dropped.
      const meta = rest.trim().match(/^(?:(\S+)(?:\s+title="([^"]*)")?)?$/);
      if (!meta) throw new Error(`${name}: unsupported fence meta "${rest.trim()}"`);
      const [, lang = "text", title] = meta;
      let label = title;
      if (group?.labels) {
        if (group.next >= group.labels.length) {
          throw new Error(`${name}: CodeGroup has more fences than labels`);
        }
        label = group.labels[group.next++];
      } else if (group && !title) {
        throw new Error(`${name}: fence in an unlabeled CodeGroup needs a title="..."`);
      }
      out.push(`${indent}${marker}${label ? `${lang} ${label}` : rest.trim()}`);
      continue;
    }

    if (h1 === null && line.trim()) {
      if (!line.startsWith("# ")) throw new Error(`${name}: body does not start with an H1`);
      h1 = line.slice(2).trim();
      continue;
    }

    // Guard against markup Mintlify cannot render. Inline code is masked so
    // placeholders like `lim ios delete <ID>` do not look like components.
    const prose = line.replace(/`[^`]*`/g, "");
    if (/className=/.test(prose)) throw new Error(`${name}: className in "${line.trim()}"`);
    if (/=\{/.test(prose.replace(EXPRESSION_PROPS, ""))) {
      throw new Error(`${name}: JSX expression prop in "${line.trim()}"`);
    }
    for (const tag of prose.matchAll(/<\/?([A-Za-z]\w*)[\s>/]/g)) {
      if (!ALLOWED_TAGS.has(tag[1])) throw new Error(`${name}: unsupported tag <${tag[1]}>`);
    }

    const groupOpen = line.match(/^(\s*)<CodeGroup(?: labels=\{\[(.*)\]\})?>\s*$/);
    if (groupOpen) {
      if (group) throw new Error(`${name}: nested CodeGroup`);
      group = { labels: groupOpen[2] === undefined ? null : parseLabels(groupOpen[2]), next: 0 };
      line = `${groupOpen[1]}<CodeGroup>`;
    } else if (/^\s*<\/CodeGroup>\s*$/.test(line)) {
      if (!group) throw new Error(`${name}: </CodeGroup> without opener`);
      if (group.labels && group.next !== group.labels.length) {
        throw new Error(`${name}: CodeGroup has ${group.labels.length} labels but ${group.next} fences`);
      }
      group = null;
    }

    const rewritten = rewriteLinks(line, name);
    targets.push(...rewritten.targets);
    out.push(rewritten.line);
  }
  if (fence) throw new Error(`${name}: unterminated code fence`);
  if (group) throw new Error(`${name}: unterminated CodeGroup`);
  if (h1 === null) throw new Error(`${name}: empty body`);
  return { body: out.join("\n").replace(/^\n+/, ""), targets, h1 };
}

// The H1 is the page heading on both sites; the frontmatter title labels the
// sidebar, so it only needs emitting when the two differ.
function frontmatterOf(fm, h1) {
  return [
    "---",
    `title: ${JSON.stringify(h1)}`,
    ...(h1 === fm.title ? [] : [`sidebarTitle: ${JSON.stringify(fm.title)}`]),
    `description: ${JSON.stringify(fm.description)}`,
    `icon: ${JSON.stringify(fm.icon)}`,
    "---",
    "",
    GENERATED_NOTICE,
    "",
    "",
  ].join("\n");
}

// One node per source directory. The directory's own page.mdx names the
// sidebar group; `sidebar: folderIndexBehavior: hidden` landing pages have no
// body worth publishing and only contribute group metadata.
async function readTree(dir) {
  const slug = relative(SRC_DIR, dir) || "index";
  const landing = parseFrontmatter(await readFile(join(dir, "page.mdx"), "utf8"), `${slug}/page.mdx`);
  const children = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) children.push(await readTree(join(dir, entry.name)));
  }
  return { slug, ...landing, children };
}

function emitPage(node) {
  const { body, targets, h1 } = transformBody(node.body, `${node.slug}/page.mdx`);
  outputs.set(`${node.slug}.mdx`, `${frontmatterOf(node.fm, h1)}${body}`);
  pages.add(node.slug);
  links.push(...targets.map((target) => ({ from: node.slug, target })));
  return node.slug;
}

// Navigation entries for a directory: its landing page unless hidden, then
// children by sidebar order, sub-directories as nested groups.
function buildGroup(node) {
  const entries = node.fm.hidden ? [] : [emitPage(node)];
  const byOrder = (a, b) => a.fm.order - b.fm.order || a.slug.localeCompare(b.slug);
  for (const child of [...node.children].sort(byOrder)) {
    entries.push(
      child.children.length === 0
        ? emitPage(child)
        : { group: child.fm.title, icon: child.fm.icon, pages: buildGroup(child) },
    );
  }
  return entries;
}

// Root pages (Introduction, Quickstart) form the first group; every top-level
// directory is already a group of its own.
const rootEntries = buildGroup(await readTree(SRC_DIR));
const groups = [
  { group: "Get started", pages: rootEntries.filter((e) => typeof e === "string") },
  ...rootEntries.filter((e) => typeof e !== "string"),
];

// Only referenced images are copied, so a screenshot refresh does not land in
// git twice. Downloads stay on the Next.js site: Mintlify would treat a .md
// file under the docs root as a page.
const images = new Set(links.map(({ target }) => target).filter((t) => t.startsWith("/images/")));
for (const image of images) {
  outputs.set(image.slice(1), await readFile(join(ROOT, "public", image)));
}

// Every remaining site-absolute link must resolve to an emitted page,
// otherwise Docs7 would publish a 404 the Next.js site never had.
const broken = links.filter(
  ({ target }) => !images.has(target) && !pages.has(target.replace(/\/$/, "").slice(1) || "index"),
);
if (broken.length > 0) {
  const list = broken.map(({ from, target }) => `  ${from}: ${target}`).join("\n");
  throw new Error(`links that do not resolve inside docs7/:\n${list}`);
}

const docsJson = {
  $schema: "https://mintlify.com/docs.json",
  theme: "mint",
  name: "Limrun",
  description: SITE_DESCRIPTION,
  colors: { primary: "#ff5100" },
  icons: { library: "lucide" },
  navigation: { groups },
  navbar: { links: [{ label: "Console", href: "https://console.limrun.com" }] },
  footer: { socials: { github: "https://github.com/limrun-inc" } },
};
outputs.set("docs.json", `${JSON.stringify(docsJson, null, 2)}\n`);

await rm(OUT_DIR, { recursive: true, force: true });
for (const [path, content] of outputs) {
  const target = join(OUT_DIR, path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content);
}
console.log(`Built docs7/: ${pages.size} pages, ${images.size} images`);
